### ISSUE TITLE
tests are not run properly

### ISSUE THREAD

**Issue by Hotell** [azz/jest-runner-tsc#6]
When this runner is used tests are not executed as they should 👀

**configs:**

**with `transform: ts-jest`**
```js
const { defaults } = require('jest-config')

const config = {
  transform: {
  '^.+\\.(ts|tsx)$': 'ts-jest'
 },
  testMatch: [
    ...defaults.testMatch,
    '**/__tests__/**/*.ts?(x)',
    '**/?(*.)+(spec|test).ts?(x)'
  ],
  moduleFileExtensions: [...defaults.moduleFileExtensions, 'ts', 'tsx'],
  globals: {
    'ts-jest': {
   skipBabel: true
}
  }
}

module.exports = config
```

**with `runner: 'jest-runner-tsc'`:**

```js
const { defaults } = require('jest-config')

const config = {
  runner: 'jest-runner-tsc',
  testMatch: [
    ...defaults.testMatch,
    '**/__tests__/**/*.ts?(x)',
    '**/?(*.)+(spec|test).ts?(x)'
  ],
  moduleFileExtensions: [...defaults.moduleFileExtensions, 'ts', 'tsx']
}

module.exports = config

```

**test suite run with ts-jest as transform vs just jest-runner-tsc as runner:**
![image](https://user-images.githubusercontent.com/1223799/41181754-2edd718c-6b73-11e8-8e92-1d7cd1982b59.png)

**Comment by azz** [comment]
They are different things :) ts-jest is to transform TS code into JS. jest-runner-tsc doesn't run tests, it runs the TS typechecker, so it's like a linter. You need to run both.

**Comment by azz** [comment]
https://facebook.github.io/jest/docs/en/configuration.html#projects-array-string-projectconfig
